# Generated by Django 5.1.2 on 2024-11-03 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktrackingapp', '0002_author_user_journalentry_userbook'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalentry',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='journalentry',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userbook',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='userbook',
            old_name='user_id',
            new_name='user',
        ),
    ]
