# Generated by Django 5.1.2 on 2024-11-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktrackingapp', '0003_rename_book_id_journalentry_book_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookStatues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='userbook',
            name='statues',
            field=models.IntegerField(default=0),
        ),
    ]
