# Generated by Django 5.1.2 on 2024-11-03 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktrackingapp', '0005_bookrating_userbook_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbook',
            old_name='statues',
            new_name='status',
        ),
    ]
