# Generated by Django 5.1.2 on 2024-11-23 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktrackingapp', '0008_alter_journalentry_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booktrackingapp.book'),
        ),
    ]
